### ISSUE TITLE
Adding open social template to server fails.

### ISSUE THREAD

**Issue by johnreytanquinco** [jubicoy/drupal8-docker#6]
I have made the application working.

Now what I'm trying to do is to install [Open Social ](https://www.drupal.org/project/social) on the server. And these are the steps I've done as this is just fine when I do it on my localhost and the template is installed properly.

1. Deployed the application successfully(db and web).

2. Download the Open social on my local machine and transfer it to server using webdav.

3. On the container, I replace /var/www/drupal to drupal_old.

4. Following [this installation](https://github.com/goalgorilla/drupal_social/wiki/Installing-and-updating#-11-quick-download--installation-recommended), I then rename the file /DIRECTORY/html to drupal.

5. Moved DIRECTORY contents to /var/www/ where the drupal directory we renamed from html is also included.
   - So now my /var/www/ contains all DIRECTORY contents plus folders "drupal_old",  "webdav" and "html"

6. Now when I run the route again, it says: File not found.

AND this is the error I received from the logs:

```
2017/03/23 09:31:35 [error] 60#60: *102 FastCGI sent in stderr: "PHP message: PHP Warning:  include(/var/www/vendor/composer/../../html/core/lib/Drupal/Core/DrupalKernel.php): failed to open stream: No such file or directory in /var/www/vendor/composer/ClassLoader.php on line 440
PHP message: PHP Warning:  include(): Failed opening '/var/www/vendor/composer/../../html/core/lib/Drupal/Core/DrupalKernel.php' for inclusion (include_path='.:/usr/share/php') in /var/www/vendor/composer/ClassLoader.php on line 440
PHP message: PHP Fatal error:  Uncaught Error: Class 'Drupal\Core\DrupalKernel' not found in /var/www/drupal/index.php:16
Stack trace:
#0 {main}
  thrown in /var/www/drupal/index.php on line 16" while reading response header from upstream, client: 172.17.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "drupal8os-myproject.192.168.64.2.nip.io"
172.17.0.1 - - [23/Mar/2017:09:31:35 +0000] "GET / HTTP/1.1" 500 5 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"
2017/03/23 09:31:50 [info] 60#60: *102 client 172.17.0.1 closed keepalive connection (104: Connection reset by peer)
```

If the route runs as expected, I will then use the database credentials on the template.

**Comment by jesseik** [comment]
This is Docker image for Drupal8 for Openshift. Changes made to running Docker instance are not persistent by default. Try to fork the Dockerfile and install Open Social with Docker. At Dockerfile install Open Social with composer, and add similar symlinks to new Drupal location if you wan't persisting themes and modules.
Remember to configure Nginx with new Drupal location as well.
