### ISSUE TITLE
Installation failed using Drupal docker image

### ISSUE THREAD

**Issue by johnreytanquinco** [jubicoy/drupal8-docker#8]
I believe my concern is a bit unrelated to this repo but Im interested to know since this is about installing Drupal 8 in OpenShift, why it fails after installing a docker image I pulled [here.](https://hub.docker.com/r/goalgorilla/open_social_docker/``)

Adding the application:
`oc new-app goalgorilla/open_social_docker
`

I am getting this error in the container logs.
```
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.6. Set the 'ServerName' directive globally to suppress this message
(13)Permission denied: AH00072: make_sock: could not bind to address [::]:80
(13)Permission denied: AH00072: make_sock: could not bind to address 0.0.0.0:80
no listening sockets available, shutting down
AH00015: Unable to open logs
```
Thanks! Appreciate your advance response!

**Comment by jesseik** [comment]
You cannot bind to port 80 without being root, which you cannot be in Openshift.
For more information take a look at the Openshift documentation here: https://docs.openshift.com/

**Comment by johnreytanquinco** [comment]
Isn't granting service account access to the project will solve the root issue?
https://docs.openshift.org/latest/admin_guide/manage_scc.html#grant-a-service-account-access-to-the-privileged-scc
